server_base_url: "http://localhost:5953"
server_port: "5953"
server_api_key: "asdf"
server_cookie_secret: "asdf="
server_cookie_secret_message: "why"
admin_username: "asdf"
admin_password: "asdf"
time_zone: "America/New_York"
bolt_db_path: "./bolt.db"
bolt_db_encryption_key: "asdf"